### PR TITLE
add .pom (for maven)

### PR DESCRIPTION
**Pull request by micycle1**

### CODE REVIEW

**Comment by KrabCode** [comment]
I'm just worried about the version inside pom.xml not being updated automatically as I release new ones... could you maybe find a way to use the prettyVersion from library.properties in there as a variable somehow? You could still put SNAPSHOT at the end...

**Comment by KrabCode** [comment]
idk, maybe the version variable there is better for that, maybe maven versions wouldn't like the 'v'

**Comment by micycle1** [comment]
Yeah, it's something you'd have to to increment manually I think.
It's not if you forget, since people can use https://jitpack.io/, which versions based on the commit hash or github release number (ignoring the project's pom).

**Comment by KrabCode** [comment]
oh, I see... alright, well if I don't have to maintain it or upload anything anywhere then I'm fine with it :) 
I'll resolve the conflicts and approve this PR

**Pull request merged**
